<a href="https://colab.research.google.com/github/syedryaaan/data_science/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dct={
    'name' : ['tom','nick','krish','jack'],
    'age' : [20,21,19,18],
    'roll' : [1,2,3,4]
}


df = pd.DataFrame(dct)

df1 = pd.DataFrame(dct)
df2 = pd.DataFrame(dct,index=['a','b','c','d'])

display(df)
display(df1)
display(df2)

    name  age  roll
0    tom   20     1
1   nick   21     2
2  krish   19     3
3   jack   18     4

    name  age  roll
0    tom   20     1
1   nick   21     2
2  krish   19     3
3   jack   18     4

    name  age  roll
a    tom   20     1
b   nick   21     2
c  krish   19     3
d   jack   18     4

In [ ]:
import pandas as pd

df=pd.read_csv('student_data.csv')
df.head(2)
df.info()
df.describe()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

# New section

In [ ]:
import pandas as pd
df = pd.read_csv('student_data.csv')
df.tail(3)




df[['study_hours','internet_usage']]




df[['study_hours','internet_usage']]

df.study_hours

0        7
1        4
2       11
3        8
4        5
        ..
9995     2
9996     7
9997    10
9998    10
9999     2
Name: study_hours, Length: 10000, dtype: int64

In [ ]:
import pandas as pd
df = pd.read_csv('student_data.csv')
df.tail(3)


df.iloc[0:   5]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [ ]:
import pandas as pd
df = pd.read_csv('student_data.csv')
# df.tail(3)


df.loc[df['study_hours'] == 11,['sleep_hours']]

      sleep_hours
2               7
9               4
10              8
29              9
30              5
...           ...
9969            8
9971            9
9978            8
9979            9
9988            6

[868 rows x 1 columns]

In [ ]:
import pandas as pd
df = pd.read_csv('student_data.csv')


df.loc[df['attendance']== 56,['study_hours']] .iloc[4:8]

     study_hours
88             1
131            3
157            1
171            3

In [ ]:
import pandas as pd
df = pd.read_csv('student_data.csv')

df.loc[df['assignments_completed']==8].iloc[2]

study_hours                   4
attendance                   98
sleep_hours                   9
internet_usage                2
assignments_completed         8
previous_score               70
exam_score                100.0
placement_status         Placed
Name: 13, dtype: object

In [ ]:
df = pd.read_csv('student_data.csv')

df[df["assignments_completed"] >3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
df = pd.read_csv('student_data.csv')



df["age"] = 20

df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [ ]:
df = pd.read_csv('student_data.csv')
df['age'] = 20
df=df.rename(columns={'assignments_completed' : 'homework'})

df

,study_hours,attendance,sleep_hours,internet_usage,homework,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [ ]:
df = pd.read_csv('student_data.csv')
df['age'] = 20
df.rename(columns={'assignments_completed' : 'homework'}, inplace = True)

df

,study_hours,attendance,sleep_hours,internet_usage,homework,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [ ]:
df = pd.read_csv('student_data.csv')
df['age'] = 20
df.rename(columns={'assignments_completed' : 'homework','study_hours':'works'}, inplace = True)

df

,works,attendance,sleep_hours,internet_usage,homework,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [ ]:
df = pd.read_csv('student_data.csv')

df.drop('study_hours',axis=1)

,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,56,8,7,10,62,100.00,Placed
1,69,5,3,8,56,100.00,Placed
2,60,7,6,10,45,100.00,Placed
3,99,9,8,4,55,90.17,Placed
4,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...
9995,58,9,7,8,88,69.31,Not Placed
9996,98,6,9,4,87,100.00,Placed
9997,44,8,5,10,37,95.94,Placed
9998,75,7,5,8,52,88.61,Placed
9999,70,6,11,16,52,78.96,Placed

In [ ]:
import pandas as pd
dct={
    'name' : ['tom','nick','krish','jack'],
    'age' : [50,50,None,50],

}


df = pd.DataFrame(dct)




df=df.dropna()
df

   name   age
0   tom  50.0
1  nick  50.0
3  jack  50.0

In [ ]:
import pandas as pd


df = pd.read_csv('student_data.csv')

In [ ]:
df.groupby('placement_status')['placement_status'].agg('count')

placement_status
Not Placed    1644
Placed        8356
Name: placement_status, dtype: int64

In [ ]:
df.groupby('placement_status')['placement_status'].agg('count')

placement_status
Not Placed    1644
Placed        8356
Name: placement_status, dtype: int64

In [ ]:
df.groupby('placement_status')['exam_score'].agg('mean')

placement_status
Not Placed    59.804653
Placed        91.996556
Name: exam_score, dtype: float64

In [ ]:
df.groupby('placement_status')['exam_score'].agg('sum')

placement_status
Not Placed     98318.85
Placed        768723.22
Name: exam_score, dtype: float64

In [ ]:
df.groupby('placement_status')['sleep_hours'].agg("max")

placement_status
Not Placed    9
Placed        9
Name: sleep_hours, dtype: int64

In [ ]:
df.groupby('study_hours')['exam_score'].mean()

study_hours
1     71.264562
2     75.169142
3     78.974939
4     81.845483
5     84.964142
6     88.620043
7     90.539568
8     93.297697
9     95.462126
10    96.574628
11    97.303283
Name: exam_score, dtype: float64

In [ ]:
def grade(x):
  if x>=90:
   return 'a'
  elif x>=80:
   return 'b'
  elif x>=70:
   return'c'
  elif x>=60:
   return'd'
  elif x>=50:
   return'e'
  else:
   return'f'

df['grade'] = df['exam_score'].apply(grade)
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,grade
0,7,56,8,7,10,62,100.00,Placed,a
1,4,69,5,3,8,56,100.00,Placed,a
2,11,60,7,6,10,45,100.00,Placed,a
3,8,99,9,8,4,55,90.17,Placed,a
4,5,52,8,6,8,40,78.82,Placed,c
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,d
9996,7,98,6,9,4,87,100.00,Placed,a
9997,10,44,8,5,10,37,95.94,Placed,a
9998,10,75,7,5,8,52,88.61,Placed,b
9999,2,70,6,11,16,52,78.96,Placed,c

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
     'id': [1,2,3,4],
     'name' : ['rahul','kabir','rayyan','syed'],
     'age' :  [25,30,35,40]
}
)


df2 = pd.DataFrame({
    'id' : [3,4,5,6],
    'name':['kabir','rayyan','syed','vamshi'],
    'age':[25,30,35,40]
})


df3 = pd.merge(df1,df2,on = 'id',how = 'inner')
df3 = pd.merge(df1,df2,on = 'id',how = 'left')
df3 = pd.merge(df1,df2,on = 'id',how = 'right')
df3 = pd.merge(df1,df2,on = 'id',how = 'outer')
print(df3)

   id  name_x  age_x  name_y  age_y
0   1   rahul   25.0     NaN    NaN
1   2   kabir   30.0     NaN    NaN
2   3  rayyan   35.0   kabir   25.0
3   4    syed   40.0  rayyan   30.0
4   5     NaN    NaN    syed   35.0
5   6     NaN    NaN  vamshi   40.0

In [ ]:
import pandas as pd
df1 = pd.DataFrame({
     'id': [1,2,3,4],
     'name' : ['rahul','rhea','ravi','raja'],
     'age' :  [25,30,35,40]
}
)


df2 = pd.DataFrame({
    'id' : [3,4,5,6],
    'name':['kabir','rayyan','syed','vamshi'],
    'age':[25,30,35,40]
})


df= pd.concat([df1, df2])

display(df)

   id    name  age
0   1   rahul   25
1   2    rhea   30
2   3    ravi   35
3   4    raja   40
0   3   kabir   25
1   4  rayyan   30
2   5    syed   35
3   6  vamshi   40

In [ ]:
import pandas as pd
df = pd.read_csv('student_data.csv')
df.pivot_table(columns='placement_status',index='sleep_hours',values='exam_score',aggfunc='mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [ ]:
import pandas as pd
df = pd.read_csv('student_data.csv')
df.pivot_table(columns='study_hours',index='sleep_hours',values='assignments_completed',aggfunc='mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844

In [ ]:
print("node.js")

node.js